# Header
menu:
  Home Page: /
  All articles: /archives
  Excerpt: /tags/excerpt

# SubNav
subnav:
  github: "https://github.com/LuShuai"
  weibo: "http://www.weibo.com/61663889"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "shuailu@yahoo-inc.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "https://www.linkedin.com/pub/shuai-lu/65/414/a81"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: ""
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  cool shell: http://coolshell.cn
  coderfengyun: http://coderfengyun.github.io

#是否开启“关于我”。
#不开启——
aboutme: true
#开启——
aboutme: In doing, we learn.
